objects/PRX_Approvals__c.object
<CustomObject>
    <fields>
        <fullName>PRX_Approval_Type__c</fullName>
        <description>Approval Types</description>
        <inlineHelpText>Approval Types</inlineHelpText>
        <label>Approval Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pricing Telco Fix</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Telco Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing ICT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance CORP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complex Bid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Check</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PRX_Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Approval</relationshipLabel>
        <relationshipName>Approval</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Approvals</label>
    <nameField>
        <label>Approvals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <recordTypes>
        <fullName>Pricing</fullName>
        <active>true</active>
        <description>Chatter Group(s) - Pricing - Telco Fix, Pricing - Telco Mobile, Pricing - ICT</description>
        <label>Pricing</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PRX_OpportunityApprovalHandler_Test.cls
@isTest
public class PRX_OpportunityApprovalHandler_Test {
    static testMethod void validateOpportunityApproval() {
        Test.startTest();
        Account accObj = new Account(Name='TestAccount');
        insert accObj;
        
        Opportunity oppObj = new Opportunity(Name='TestOpportunity', 
                             AccountId=accObj.id , CloseDate=(system.today()+2),
                             StageName='Prospecting');
        insert oppObj;
        
        Id recordTypeId = Schema.SObjectType.PRX_Approvals__c.getRecordTypeInfosByName().get('Pricing').getRecordTypeId();
        PRX_Approvals__c appObj = new PRX_Approvals__c(Name='Test_Approval1', RecordTypeId=recordTypeId,
                                  PRX_Approval_Type__c='Pricing Telco Fix',PRX_Opportunity_Name__c=oppObj.Id);
        insert appObj;
        PRX_SystemUtility.sysLog('PRX_OpportunityApprovalHandler_Test' , 'Exception' , '123');
        PRX_VariableConstant c = new PRX_VariableConstant();
        Test.stopTest(); 
    }
    
    static testMethod void validateOpportunityApproval_N() {
        Test.startTest();
        Account accObj = new Account(Name='TestAccount');
        insert accObj;
        
        Opportunity oppObj = new Opportunity(Name='TestOpportunity', 
                             AccountId=accObj.id , CloseDate=(system.today()+2),
                             StageName='Prospecting');
        insert oppObj;
        
        Id recordTypeId = Schema.SObjectType.PRX_Approvals__c.getRecordTypeInfosByName().get('Pricing').getRecordTypeId();
        PRX_Approvals__c appObj = new PRX_Approvals__c(Name='Test_Approval1', RecordTypeId=recordTypeId,
                                  PRX_Approval_Type__c='Pricing Telco Fix',PRX_Opportunity_Name__c=oppObj.Id);
        insert appObj;
        update appObj;
        delete appObj;
        Test.stopTest();
    }
}