objects/PRX_SystemLog__c.object
<CustomObject>
    <description>Object used to hold exception details from trigger and class, implement PRX_SystemUtility class methods</description>
    <fields>
        <fullName>Log_Type__c</fullName>
        <description>Used to distinguish the type of log.</description>
        <label>Log Type</label>
        <picklist>
            <picklistValues>
                <fullName>Exception</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UserLog</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Originating_Class_Name__c</fullName>
        <description>Used to capture the class name from where its logged</description>
        <label>Originating Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Running_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To capture the running user</description>
        <label>Running User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PRX_SystemLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>Full stack trace of the exception(trim at 131000)</description>
        <label>Stack Trace</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <label>PRX_SystemLog</label>
    <nameField>
        <displayFormat>SL-{000000000}</displayFormat>
        <label>PRX_SystemLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRX_SystemLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PRX_SystemUtility.cls
/*
 * Class PRX_SystemUtility 
 *
 * Class used for System related methods and reusable code.
 */
public class PRX_SystemUtility {
    
    /*
    * Name: checkOpprtunityBeforeAddUpdateDelete
    * Description: Used to check and add error for CR3239
    * Author: Ankit
    */
    public static void checkOpprtunityBeforeAddUpdateDelete(List<sObject> oppLineList , String currentUserprofile , Set<String> adminProfileToNotRestrict , Set<String> opprtunityStageRestrictName , Map<Id,Opportunity> oppLineIdWithOpportunity , String customErromsg){
        system.debug('---1---' + adminProfileToNotRestrict.contains(currentUserprofile));
        system.debug('---2---' + opprtunityStageRestrictName);
        for(SObject opp : oppLineList){
            if(!adminProfileToNotRestrict.contains(currentUserprofile) && opprtunityStageRestrictName.contains((String)oppLineIdWithOpportunity.get(opp.Id).get('StageName'))){
                system.debug('---3---');
                opp.addError(customErromsg + (String)oppLineIdWithOpportunity.get(opp.Id).get('StageName'));
            }
        }
    }
    
    /*
    * Name: sysLog
    * Description: Used to insert log object
    * Author: Ankit
    */
    public static void sysLog(String originatingClassName , String logType , String stack ){
        if(String.isNotBlank(originatingClassName) && String.isNotBlank(logType) && String.isNotBlank(stack)){
            stack = stack.length() > 131000 ? stack.substring(0,131000) : stack;
            PRX_SystemLog__c sysObj = new PRX_SystemLog__c(
                                        Originating_Class_Name__c=originatingClassName , Log_Type__c=logType ,
                                        Stack_Trace__c=stack , Running_User__c=userinfo.getUserId());
            insert sysObj;
        }
    }
}